DROP TABLE IF EXISTS USER_TBL;
CREATE TABLE USER_TBL (id bigint generated by default as identity, display_name varchar(255), password varchar(255) not null, username varchar(255) not null, primary key (id));

DROP TABLE IF EXISTS BLOG;
CREATE TABLE BLOG (id bigint generated by default as identity, text varchar(255), title varchar(255), user_id bigint, primary key (id));

DROP TABLE IF EXISTS BLOG_TAGS;
CREATE TABLE BLOG_TAGS (blog_id bigint not null, tag_id bigint not null, primary key (blog_id, tag_id));

DROP TABLE IF EXISTS TAG;
CREATE TABLE TAG (id bigint generated by default as identity, name varchar(255), primary key (id));

DROP TABLE IF EXISTS TOKEN;
CREATE TABLE TOKEN (id bigint generated by default as identity, is_expired boolean not null, token varchar(255), user_id bigint, primary key (id));
